Modify the debconf part to prompt user for its network configuration Handle routes and addresses dynamically

diff --git a/platine-daemon/scripts/st_netinit b/platine-daemon/scripts/st_netinit
--- a/platine-daemon/scripts/st_netinit
+++ b/platine-daemon/scripts/st_netinit
@@ -6,17 +6,33 @@ CMD=$1
 #
 # This script is used to initialize the Platine network on ST
 #
-# Authors Eddy Fromentin (AQL)
-#         Olivier Alphand
-#         Didier Barvaux <didier.barvaux@toulouse.viveris.com>
-#         Cedric Baudoin <cedric.baudoin@thalesaleniaspace.com>
-#         Julien Bernard <julien.bernard@toulouse.viveris.com>
+# Authors Julien Bernard <julien.bernard@toulouse.viveris.com>
 
 # Source debconf library.
 . /usr/share/debconf/confmodule
 
-# maximum number of lan
-NB_LAN=5
+# Source default library
+SYSCTL="true"
+# ICMP redirects
+# TODO check if it is necessary
+SEND_REDIRECTS="0"
+ACCEPT_REDIRECTS="0"
+
+# Forwarding: necessary to be able to forward satellite trafic toward
+# workstations
+IP_FORWARD="1"
+FORWARDING="1"
+
+# UDP buffer size: incresed to support high traffic
+WMEM_MAX="1048580"
+RMEM_MAX="1048580"
+WMEM_DEFAULT="1048580"
+RMEM_DEFAULT="1048580"
+if [ -f /etc/default/platine-network ]; then
+    . /etc/default/platine-network
+fi
+
+DHCP_CONFIG_FILE="/var/cache/dnsmasq/lan_st.conf"
 
 # load the configuration file
 load_conf(){
@@ -26,47 +42,70 @@ load_conf(){
         db_get platine-daemon/service/st_instance
         export LAN=$RET
     else
-        export LAN=2
+        export LAN=0
     fi
     db_get platine-daemon/network/emu_iface
     export EMU_IFACE=$RET
-    db_get platine-daemon/network/emu_ipv4
-    export EMU_IPV4=$RET
-    db_get platine-daemon/network/emu_ipv6
-    export EMU_IPV6=$RET
     db_get platine-daemon/network/lan_iface
     export LAN_IFACE=$RET
-    db_get platine-daemon/network/lan_ipv4
-    export LAN_IPV4=$RET
-    db_get platine-daemon/network/lan_ipv6
-    export LAN_IPV6=$RET
-    # network parameters
-    #TODO useful?? correct??
-    let IPV6_LOC=0x278b+$LAN
-    export IPV6_LOC
+    db_get platine-daemon/network/config_level
+    config=$RET
+    if [ "$config" != "AUTOMATIC" ]; then
+        db_get platine-daemon/network/lan_ipv4
+        export LAN_IPV4=$RET
+        db_get platine-daemon/network/lan_ipv6
+        export LAN_IPV6=$RET
+    else
+        export LAN_IPV4=`ip addr show ${LAN_IFACE} | grep -o -e "inet [^ ]*" | \grep -o -e "[^ ]*$"`
+        export LAN_IPV6=`ip addr show ${LAN_IFACE} | grep global | grep -o -e "inet6 [^ ]*" | grep -o -e "[^ ]*$"`
+    fi
+
+    db_get platine-daemon/network/dhcp
+    export DHCP=$RET
+
+    # host name
+    if [ "$LAN" = "0" ]; then
+        export NAME='GW'
+    else
+        export NAME='ST'$LAN
+    fi
+
+
+    # TUN0 parameters
+    # TUN0 address is lan address + 2 (+1 before module and +1 after to avoid 0)
+    export LAN4=${LAN_IPV4%/*}
+    export MASK4=${LAN_IPV4##*/}
+    export TUN0_IFACE='platine'
+    # the address elements LAN4=net4.add4
+    net4=${LAN4%.*}
+    add4=${LAN4##*.}
+    # Do as if the mask is /24 when it is smaller
+    if [ ${MASK4} -le 24 ]; then
+        modulo=254
+    # we need enough addresses for eth interface, tun interface and some WS
+    elif [ ${MASK4} -ge 30 ]; then 
+        halt_on_error "the ST lan IPv4 mask should be smaller than 30"
+    else
+        modulo=$((2 ** (32-${MASK4}) - 2))
+    fi
+    export TUN0_IPV4="${LAN4%.*}.$(((${LAN4##*.} + 1 % ${modulo}) +1))/${MASK4}"
+    lan6=${LAN_IPV6%/*}
+    mask6=${LAN_IPV6##*/}
+
+    # Do as if the mask is /112 when it is smaller
+    if [ ${MASK4} -le $((0xFFFE)) ]; then
+        modulo=0xFFFE
+    # we need enough addresses for eth interface, tun interface and some WS
+    elif [ ${MASK4} -ge  126 ]; then 
+        halt_on_error "the ST lan IPv6 mask should be smaller than 126"
+    else
+        modulo=$(($((2**$((256-${mask6}))))-2))
+    fi
+
+    export TUN0_IPV6="${lan6%:*}:`printf '%x' $(((0x${lan6##*:} + 1 % ${modulo}) + 1))`/${mask6}"
 
     # modules
     export MODULES='ip6_tables'
- 
-    # host name
-    export NAME='ST'$LAN
- 
-    # TODO load mask from debconf
-    # interfaces parameters
-    #  with sat
-    export EMU_IPV4_MASK=255.255.255.0
-    export EMU_IPV4_BRD=192.168.18.255
-    export EMU_IPV6=$EMU_IPV6/64
-    #  with lan
-    export LAN_IPV4_MASK=255.255.255.0
-    export LAN_IPV4_BRD=${LAN_IPV4%.*}.255
-    export LAN_IPV6=$LAN_IPV6/64
-    export LAN_IPV6_NET=${LAN_IPV6%:*}:0/64
-    #  tun0
-    export TUN0_IFACE='platine'
-    export TUN0_IPV4=${LAN_IPV4%.*}.4
-    export TUN0_IPV6_GLOB=${LAN_IPV6%:*}:4
-    export TUN0_IPV6_LOC=fe80::f893:34ff:fe89:$(printf "%X" $IPV6_LOC)
 }
 
 
@@ -80,7 +119,7 @@ usage(){
     echo "        CHECK   show the network configuration"
     echo "        RESET   blank the network configuration"
     echo
-    return 
+    return
 }
 
 halt_on_error(){
@@ -101,7 +140,7 @@ evecho(){
     return
 }
 
-# Check if the user running this script is root. 
+# Check if the user running this script is root.
 # Exit if not
 #
 check_root(){
@@ -114,19 +153,13 @@ check_root(){
 # Roughly reset network configuration
 #
 reset_conf() {
-    echo "# Reset Platine network configuration"
-    /sbin/iptables -F 
-    /sbin/ip6tables -F
-    /sbin/ip6tables -F -t mangle
-    /sbin/ip route flush dev $EMU_IFACE
-    /sbin/ip route flush dev $LAN_IFACE
+    echo "# Reset Platine TUN0 interface configuration"
+    /sbin/iptables -D FORWARD -i $TUN0_IFACE -o $TUN0_IFACE -j DROP
+    /sbin/ip6tables -D FORWARD -i $TUN0_IFACE -o $TUN0_IFACE -j DROP
     /sbin/ip route flush dev $TUN0_IFACE
-    /sbin/ip -6 route flush dev $EMU_IFACE
-    /sbin/ip -6 route flush dev $LAN_IFACE
     /sbin/ip -6 route flush dev $TUN0_IFACE
-    /sbin/ifconfig $EMU_IFACE 0 down
-    /sbin/ifconfig $LAN_IFACE 0 down
     /sbin/ifconfig $TUN0_IFACE 0 down
+    /bin/rm -f ${DHCP_CONFIG_FILE}
     return
 }
 
@@ -151,132 +184,199 @@ check_conf(){
     /sbin/ifconfig -a
     /sbin/ip route
     /sbin/ip -6 route
-    /sbin/iptables -n -v -L 
-    /sbin/ip6tables -n -v -L 
-     
+    /sbin/iptables -n -v -L
+    /sbin/ip6tables -n -v -L
+
     return
 }
 
 set_rules(){
-    # - DROP packets routed from the tun0 to tun0 
-    # TBD is there any loop ? what happens if tun do not forward packets
+    # - DROP packets routed from the tun0 to tun0
     evecho /sbin/iptables -A FORWARD -i $TUN0_IFACE -o $TUN0_IFACE -j DROP
     evecho /sbin/ip6tables -A FORWARD -i $TUN0_IFACE -o $TUN0_IFACE -j DROP
-     
+
     # - DROP multicast packets
-    # tested    
     # evecho /sbin/ip6tables -A INPUT -i $TUN0_IFACE -s $TUN0_IPV6_LOC/128 -d ff00::/8 -j DROP
-   
-    return
-}
-
-# Set iptables rules in order to queue incoming multicast packet
-# disallow the resending of mcast packets (this is done by the st software)
-set_multicast_routes(){
-#    ipv4_mcast="239.255.42.1 239.255.42.2 239.255.42.3 239.255.42.4 239.255.42.5"
-#    ipv6_mcast="ff08::1 ff08::2 ff08::3 ff08::4 ff08::5"
-
-    echo "#   Configuring st tables for multicast"
-    for group in $ipv4_mcast
-    do
-        evecho route add $group dev $LAN_IFACE
-    done
-
-    for group in $ipv6_mcast
-    do
-        evecho route -A inet6 add $group dev $LAN_IFACE
-    done
 
     return
 }
 
-# Set route to others st and sublan
-# TODO if ip address can be changed, remove that, this should be done
-# dynamically by the daemon
-set_route_to_others(){
-    echo "#   Configuring routes to other networks"
-    # del the automatic route in ipv6
-    evecho /sbin/ip -6 route del $LAN_IPV6_NET dev $TUN0_IFACE
-
-    for lan_dest in `seq 1 $NB_LAN` ; do
-    if [ $lan_dest != $LAN ]; then
-        echo "#    Configuring lan destination $lan_dest"
-
-        let ipv4_dest_net=18+$lan_dest
-        let ipv6_dest_net=101+$lan_dest
-
-        eval typeset lan_dest_ipv4=192.168.$ipv4_dest_net.0/24
-        eval typeset lan_dest_ipv6=2001:660:6602:$ipv6_dest_net::0/64
-
-        # ROUTE
-        evecho /sbin/route add -net $lan_dest_ipv4 dev $TUN0_IFACE
-        eval typeset  other_net_ipv6='$IPv6_LAN'$lan
-        evecho /sbin/ip -6 route add $lan_dest_ipv6 dev $TUN0_IFACE
-    fi
-    done
-}
 
 # Configure the interfaces
 set_interfaces(){
-    evecho /sbin/ifconfig $LAN_IFACE $LAN_IPV4 netmask $LAN_IPV4_MASK broadcast $LAN_IPV4_BRD
-    evecho /sbin/ifconfig $EMU_IFACE $EMU_IPV4 netmask $EMU_IPV4_MASK broadcast $EMU_IPV4_BRD
+    echo "Set $LAN_IFACE up"
     evecho /sbin/ifconfig $LAN_IFACE up
+    echo "Set $EMU_IFACE up"
     evecho /sbin/ifconfig $EMU_IFACE up
-    evecho /sbin/ifconfig $EMU_IFACE add $EMU_IPV6
-    evecho /sbin/ifconfig $LAN_IFACE add $LAN_IPV6
+    echo "Set $TUN0_IFACE up"
     evecho /sbin/ifconfig $TUN0_IFACE up
+    echo "Assign $TUN0_IPV4 and $TUN0_IPV6 addresses on $TUN0_IFACE interface"
     evecho /sbin/ifconfig $TUN0_IFACE $TUN0_IPV4
-    evecho /sbin/ifconfig $TUN0_IFACE add $TUN0_IPV6_GLOB/64
-    # TODO is this local address really useful ?
-    evecho /sbin/ifconfig $TUN0_IFACE add $TUN0_IPV6_LOC/64
+    evecho /sbin/ifconfig $TUN0_IFACE add $TUN0_IPV6
 
     return
 }
 
+#TODO try to remove redirects modifs
 # Configure sysctl
 set_sysctl(){
     # disable ICMP redirect
-    evecho /sbin/sysctl -w "net/ipv4/conf/all/send_redirects"="0"
-    evecho /sbin/sysctl -w "net/ipv4/conf/$TUN0_IFACE/send_redirects"="0"
-    evecho /sbin/sysctl -w "net/ipv4/conf/all/accept_redirects"="0"
-    evecho /sbin/sysctl -w "net/ipv6/conf/all/accept_redirects"="0"
-    evecho /sbin/sysctl -w "net/ipv4/conf/$TUN0_IFACE/accept_redirects"="0"
-    evecho /sbin/sysctl -w "net/ipv6/conf/$TUN0_IFACE/accept_redirects"="0"
+    echo -n  "Set send_redirects=$SEND_REDIRECTS on "
+    echo "$EMU_IFACE, $LAN_IFACE and $TUN0_IFACE intefaces"
+    evecho /sbin/sysctl -w "net/ipv4/conf/$EMU_IFACE/send_redirects"=$SEND_REDIRECTS
+    evecho /sbin/sysctl -w "net/ipv4/conf/$LAN_IFACE/send_redirects"=$SEND_REDIRECTS
+    evecho /sbin/sysctl -w "net/ipv4/conf/$TUN0_IFACE/send_redirects"=$SEND_REDIRECTS
+
+    echo -n  "Set accept_redirects=$ACCEPT_REDIRECTS on "
+    echo "$EMU_IFACE, $LAN_IFACE and $TUN0_IFACE intefaces"
+    evecho /sbin/sysctl -w "net/ipv4/conf/$EMU_IFACE/accept_redirects"=$ACCEPT_REDIRECTS
+    evecho /sbin/sysctl -w "net/ipv4/conf/$LAN_IFACE/accept_redirects"=$ACCEPT_REDIRECTS
+    evecho /sbin/sysctl -w "net/ipv4/conf/$TUN0_IFACE/accept_redirects"=$ACCEPT_REDIRECTS
+    evecho /sbin/sysctl -w "net/ipv6/conf/$EMU_IFACE/accept_redirects"=$ACCEPT_REDIRECTS
+    evecho /sbin/sysctl -w "net/ipv6/conf/$LAN_IFACE/accept_redirects"=$ACCEPT_REDIRECTS
+    evecho /sbin/sysctl -w "net/ipv6/conf/$TUN0_IFACE/accept_redirects"=$ACCEPT_REDIRECTS
+
     # enable forwarding
-    evecho /sbin/sysctl -w "net/ipv4/ip_forward"="1"
-    evecho /sbin/sysctl -w "net/ipv4/conf/all/forwarding"="1"
-    evecho /sbin/sysctl -w "net/ipv6/conf/all/forwarding"="1"
-    # increase TCP buffers
-    evecho /sbin/sysctl -w "net/core/wmem_max"="1048580"
-    evecho /sbin/sysctl -w "net/core/rmem_max"="1048580"
-    evecho /sbin/sysctl -w "net/core/wmem_default"="1048580"
-    evecho /sbin/sysctl -w "net/core/rmem_default"="1048580"
+    echo "Set ip_forward=$IP_FORWARD"
+    evecho /sbin/sysctl -w "net/ipv4/ip_forward"=$IP_FORWARD
+    echo -n  "Set forwarding=$FORWARDING"
+    echo "$EMU_IFACE, $LAN_IFACE and $TUN0_IFACE intefaces"
+    evecho /sbin/sysctl -w "net/ipv4/conf/$EMU_IFACE/forwarding"=$FORWARDING
+    evecho /sbin/sysctl -w "net/ipv4/conf/$LAN_IFACE/forwarding"=$FORWARDING
+    evecho /sbin/sysctl -w "net/ipv4/conf/$TUN0_IFACE/forwarding"=$FORWARDING
+    evecho /sbin/sysctl -w "net/ipv6/conf/$EMU_IFACE/forwarding"=$FORWARDING
+    evecho /sbin/sysctl -w "net/ipv6/conf/$LAN_IFACE/forwarding"=$FORWARDING
+    evecho /sbin/sysctl -w "net/ipv6/conf/$TUN0_IFACE/forwarding"=$FORWARDING
+
+    # increase UDP buffers
+    echo "Set wmem_max=$WMEM_MAX"
+    evecho /sbin/sysctl -w "net/core/wmem_max"=$WMEM_MAX
+    echo "Set rmem_max=$RMEM_MAX"
+    evecho /sbin/sysctl -w "net/core/rmem_max"=$RMEM_MAX
+    echo "Set wmem_default=$WMEM_DEFAULT"
+    evecho /sbin/sysctl -w "net/core/wmem_default"=$WMEM_DEFAULT
+    echo "Set rmem_default=$RMEM_DEFAULT"
+    evecho /sbin/sysctl -w "net/core/rmem_default"=$RMEM_DEFAULT
+
+    return
+}
+set_tun_sysctl(){
+    # disable ICMP redirect
+    echo "Set send_redirects=$SEND_REDIRECTS on $TUN0_IFACE inteface"
+    evecho /sbin/sysctl -w "net/ipv4/conf/$TUN0_IFACE/send_redirects"=$SEND_REDIRECTS
+
+    echo "Set accept_redirects=$ACCEPT_REDIRECTS on $TUN0_IFACE inteface"
+    evecho /sbin/sysctl -w "net/ipv4/conf/$TUN0_IFACE/accept_redirects"=$ACCEPT_REDIRECTS
+    evecho /sbin/sysctl -w "net/ipv6/conf/$TUN0_IFACE/accept_redirects"=$ACCEPT_REDIRECTS
+
+    # enable forwarding
+    echo "Set forwarding=$FORWARDING on $TUN0_IFACE inteface"
+    evecho /sbin/sysctl -w "net/ipv4/conf/$TUN0_IFACE/forwarding"=$FORWARDING
+    evecho /sbin/sysctl -w "net/ipv6/conf/$TUN0_IFACE/forwarding"=$FORWARDING
 
     return
 }
 
+set_dhcp_server(){
+    # check if DHCP server is enabled
+    if [ "$DHCP" != "true" ]; then
+        return
+    fi
+
+    echo "# Configure DHCP server"
+
+    full_octets=$(($1/8))
+    local partial_octet=$(($1%8))
+    mask=""
+
+    for i in `seq 1 4`; do
+        if [ $i -lt $full_octets ]; then
+            mask+=255
+        elif [ $i -eq $full_octets ]; then
+            mask+=$((256 - 2**(8-$partial_octet)))
+        else
+            mask+=0
+        fi  
+        test $i -lt 3 && mask+=.
+    done
+
+    if [ ${MASK4} -gt 27 ]; then
+        echo "mask is too high, please configure DHCP manually"
+        return
+    elif [ ${MASK4} -gt 24 ]; then
+        min=$((256 - 2**(32-${MASK4})))
+    else
+        min=0
+    fi
+
+    # range is at least based on mask /24 for more simplicity and limited to 10 hosts
+    if [ ${LAN4##*.} -gt $((min+20)) ]; then
+        range_start=${LAN4%.*}.$((min+10))
+        range_end=${LAN4%.*}.$((min+19))
+    else
+        range_start=${LAN4%.*}.$((min+21))
+        range_end=${LAN4%.*}.$((min+30))
+    fi
+
+    subnet=${LAN_IPV4%.*}
+    subnet+=.0
+    if [ ${MASK4} -gt 24 ]; then
+        cidr=24
+    elif [ ${MASK4} -gt 16 ]; then
+        subnet=${subnet%.*}
+        subnet+=".0"
+        cidr=16
+    else
+        subnet=${subnet%.*}
+        subnet=${subnet%.*}
+        subnet+=".0"
+        subnet+=".0"
+        cidr=8
+    fi
+
+    /bin/cat 2>/dev/null << EOF > "${DHCP_CONFIG_FILE}"
+
+# IP range
+dhcp-range=${range_start},${range_end},${mask},1h
+# interface name
+interface=${LAN_IFACE}
+# add classless-static-routes option to configure an automatic static route
+# 121 is the code for classless-static-routes
+# Be careful, we assume that the mask for all STs is your ST lan maks is the
+# previous mask being a power of 2 (e.g. /16 for mask from /17 to /24), if this
+# is not the case please modify it
+# If the STs are not on a same subnetwork please do no use this option and set
+# your routes manually or use the daemon
+dhcp-option=121,${cidr}.${subnet},${LAN_IPV4}
+
+EOF
+
+    if [ $? -ne 0 ] ; then
+        # not an error, this is only an exemple so it is not fatal
+        echo "Failed to write DHCP range to DHCP config file"
+    fi
+}
 
 # Configure st router
 st_config(){
     echo "# Configuring $NAME"
     load_modules
 
-    echo "# Configuring sysctl"
-    set_sysctl
+    if [ ${SYSCTL} = "true" ]; then
+        echo "# Configuring sysctl"
+        echo "  See /etc/default/platine-daemon to avoid this modifications" 
+        set_sysctl
+    fi
+    echo "# Configuring sysctl for TUN interface"
+    set_tun_sysctl
 
     echo "# Configuring interfaces"
     set_interfaces
 
-    echo "# Configuring routes"
-    # route to other lan
-    set_route_to_others
-
-    # route for multicast
-    set_multicast_routes
-
     echo "# Configuring rules"
     set_rules
 
+    set_dhcp_server
     return
 }
 
@@ -290,19 +390,22 @@ echo "# Configure Platine network for ST"
 case $CMD in
      CONF )
          load_conf
-         reset_conf
          st_config
      ;;
-     CHECK ) check_conf     ;; 
-     RESET ) 
+     CHECK )
+         load_modules
+         check_conf
+     ;;
+     RESET )
          load_conf
+         load_modules
          reset_conf
      ;;
-     *) 
+     *)
         echo "Error: unknown command $CONF"
         usage
         exit 1
     ;;
 esac
- 
+
 exit 0
