Many modifications to add Ethernet support on the platform:  - Rename IP-QoS block in LanAdaptation block and add support for plugins  - Move IP part into a plugin  - Move mandatory plugins in core (fix bugs 1015153, 1040632, 1042641)  - Add the Ethernet plugin  - Move ROHC plugin from encapsulation to lan adaptation  - Add a TAP interface and a bridge  - Handle network in daemon process instead of an init script  - Update tests (still need to add Ethernet ones)  - Update manager:    - handle new plugins    - specify to daemon if it should setup routes for TUN or bridge      interface on start    - update topology with the ethernet part    - improve stack handling Add a script to build packages automatically. Rename ATM/AAL5 into AAL5/ATM while moving it in core (fix bug 1051711)

diff --git a/opensand-daemon/init/opensand-daemon b/opensand-daemon/init/opensand-daemon
--- a/opensand-daemon/init/opensand-daemon
+++ b/opensand-daemon/init/opensand-daemon
@@ -1,7 +1,7 @@
 #!/bin/bash
 ### BEGIN INIT INFO
 # Provides:          opensand-daemon
-# Required-Start:    $remote_fs $syslog opensand-network
+# Required-Start:    $remote_fs $syslog
 # Required-Stop:     $remote_fs $syslog
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
@@ -21,15 +21,35 @@ BIN="/usr/bin/sand-daemon"
 CONF="/etc/opensand/daemon.conf"
 PIDFILE="/var/run/sand-daemon/pid"
 USER="opensand"
+CONFSCRIPT="/usr/libexec/opensand/write_initialize_config"
 
 . /lib/lsb/init-functions
 
 
+configure()
+{
+    # Check that executable is present
+    if [ ! -x ${CONFSCRIPT} ] ; then
+        log_failure_msg "OpenSAND host configuration script '${CONFSCRIPT}' not found on system"
+        log_end_msg 1
+        exit 1
+    fi
+
+    # Launch the script
+    ${CONFSCRIPT} 1>/dev/null
+    if [ $? -ne 0 ] ; then
+        log_failure_msg "failed to configure the host"
+        log_end_msg 1
+        exit 1
+    fi
+}
+
 # Start the server
 start()
 {
-    # check that opensand-network is configured
-    check_net
+    # do some configuration first
+    # we do that here for sysctl configuration reloading
+    configure
     
     log_daemon_msg "Starting ${DESCR}" "${PROGNAME}"
 
@@ -81,12 +101,8 @@ stop()
     else
         log_failure_msg "${PIDFILE} does not exist"
         log_end_msg 1
-#        exit 1
-		return
+        return
     fi
-
-    echo "Closing connections"
-    echo "Please wait..."
 
     # Wait for the daemon to stop
     for try in $(seq 1 5) ; do
@@ -127,21 +143,10 @@ stop()
 # Stop then start the server
 restart()
 {
-    stop
-    start || exit 1
-}
-
-
-check_net()
-{
-# check that network is configured
-    if [ -e /var/lock/opensand-network ]; then
-        echo -n ""
-    else
-        log_failure_msg "Please configure the OpenSAND network before starting the daemon"
-        log_end_msg 1
-        exit 1
+    if [ -f "$PIDFILE" ] ; then
+        stop
     fi
+    start || exit 1
 }
 
 # Which action to perform?
@@ -167,5 +172,6 @@ case "$1" in
 esac
 
 exit 0
+
 
 
